PLUGIN_NAME=		confic-vis
PLUGIN_VERSION=		0.1
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Config Visualiser
PLUGIN_DEPENDS=		confic-vis
PLUGIN_MAINTAINER=	jakob.seibert@univie.ac.at

.include "../../Mk/plugins.mk"